### ISSUE TITLE
Make Raft Engine production ready for TiKV

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#95]
# Development Task

As of now Raft Engine is already wired with TiKV, and can be enabled by TiKV's [raft-engine configuration group](https://github.com/tikv/tikv/blob/e0c68a70367412f0e3d717de43335c0a7e98bd37/etc/config-template.toml#L915). But we haven't announce this feature publicly, and do not encourage using it for production.

This task aims to change this situation and make raft engine ready for production. We will be tracking the progress here and the detailed design in this [internal doc](https://docs.google.com/document/d/144T3--EmpqKqP_ax4EZYstqZWQxld2vkhBI5uqoIvnQ/edit).

Staff: @tabokie @MrCroxx 

Time estimation: currently shooting for late 2021

Task breakdown:

## Interface
- [x] API for storage access
  - [x] Basic file system interface for creating IO wrapper: #91 
  - [x] Strongly typed file system interface: #96
- [x] Customized storage layer for TiKV: https://github.com/tikv/tikv/pull/10937
  - [x] Adapt encryption for Raft Engine
    - https://github.com/tikv/tikv/pull/10758
    - https://github.com/tikv/tikv/pull/10929
- [ ] API for customized thread pool (optional)
## Observability
- [x] Prometheus metering: #76
- [x] Integration with TiKV Grafana: tikv/tikv#10637
## Performance
- [x] Fast recovery: 6x faster
  - [x] New log format for recovering indexes: #83
  - [x] Parallel recovery: #97
- [x] Fast log batch encoding: 3x faster
  - [x] Streaming encoding: #91
  - [x] Reduce allocation: #98
- [x] Optimize file operation: 2.5x throughput, #100 
- [x] Benchmark and best practice for usage within TiKV
  - [x] Known issue: IOPS explosion, Fix: #116
## Safety
- [x] Improve handling of IO error: #131
- [x] Unit test
## Tools
- [x] Standalone performance benchmark: #84
- [ ] Data administration tool: #99 
## Integration test
- [x] Benchmark with TPC-C, sysbench
- [x] High pressure workload with random failures
## Misc
- [x] Remove entry cache: #77
- [x] Update README
- [ ] Compile with stable Rust (optional)
- [ ] Build on Windows (optional)

**Comment by tabokie** [comment]
Scheduled to be released in v5.4.0 as an experimental feature. Closing this.
