### ISSUE TITLE
Add administration tool for recovery from data corruption

### ISSUE THREAD

**Issue by tabokie** [tikv/raft-engine#99]
# Development Task

This task attempts to add a data administration tool similar to `ldb` offered by [RocksDB](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool).

Raft engine is unable to start when it encounters data corruption (checksum mismatch, unexpected EOF). But user might employs data redundancy at application level. So we should allow user to manually decide how to deal with corrupted data, and recover the data files to a consistent state once the affected raft groups are properly handled.

Workload estimation: M (Two man week)

Task breakdown:

- [x] Lock file: multiple processes can't operate on the same db directory simultaneously: #102
- [ ] Dump: output operations in log files
- [x] Consistency check*: scan for holes in raft group and truncate corrupted file tails: #132 
- [ ] Unsafe recover**: recover to consistent state by modifying log files
- [x] A standalone binary that encapsulates the two methods as sub-commands: #144

\* Ideally user should be able to extract the remaining log entries for more complex recovery logic, but that is too cumbersome for this phrase.

\*\* For now, we only offer three options for unsafe recovery:
1. Remove the entire raft group in question
2. Remove log entries before a given index, making the rest of log entries in consistent state
3. Fill in empty messages to repair log entry holes

**Comment by Connor1996** [comment]
Better to provide it in tikv-ctl instead of a standalone binary

**Comment by yiwu-arbug** [comment]
We also need a tool to print the content of log files, preferably if it can deserialize the protobuf Entry struct.

**Comment by tabokie** [comment]
@Connor1996 tikv-ctl can still use those public interfaces. If you consider raft engine as an independent project, then it's good to have a standalone binary too.
@yiwu-arbug User should be responsible for any protobuf parsing, raft engine only store raw blob data. So data access tool should also be implemented by user (tikv-ctl) using existing engine methods.

This issue mainly focuses on recovery from fatal error (log index or key-value corruption). For rocksdb, it's simply a matter of deleting corrupted SSTs, but for raft engine, things are more complicated because deletion of one log file might or might not break the continuum of other undamaged raft groups. So I'm inclined to handle corruption based on single region (rather than single file), and design interfaces around this assumption.

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug User should be responsible for any protobuf parsing, raft engine only store raw blob data. So data access tool should also be implemented by user (tikv-ctl) using existing engine methods.

agree tikv-ctl can implement the deserialization, but we need to include tikv-ctl change in this task or a separate task.

**Comment by yuqi1129** [comment]
@tabokie For the rest subtasks, is there any design document?

**Comment by tabokie** [comment]
@yuqi1129 No, you can first propose a set of interfaces (it's ok to use pseudo-code) for the subtasks, and from there we can further discuss the implementation details.

Just for your reference, we recover from RocksDB kvdb corruption by the following steps:
1) Get all corrupted SSTs
2) Get the key ranges of those corrupted SSTs
3) Logically remove the region peers overlapped with those ranges
4) Physically remove the corrupted files from RocksDB

For raftdb, we don't have a recovery routine yet, but the process should be similar:
1) Get all corrupted raft groups
2) Gather information of those raft groups
3) Do user recovery routine
4) Physically remove the corrupted data and make raft engine bootable again

The subtask you created is essentially step 1 and 2.
